### ISSUE TITLE
Spy/bullet/ninja issues

### ISSUE THREAD

**Issue by eyMiko** [Donhavich/CS-project#10]
When a the spy is standing next to a ninja, and shoots at any other direction, the spy is still alive when its supposed to be killed because of the adjacent ninja. Also, the counter for the spy's life is one off, because it has 4 lives instead of 3. The game ends when the spy's life is -1 instead of 0.  The bullet item works when the spy is out of ammo, but when the spy has one ammo, instead of being 2 ammo when being picked up, the ammo count stays at 1. Also, every time the spy dies and respawns, his bullet count gets reset to 1. I know we're supposed to keep him in the same position after he dies, but is he bullet count supposed to stay the same or is it suppose to reset? Also, I don't know if this is an issue, but when the spy is surrounded by multiple ninjas, he loses his lives quicker within a turn. I went from 2 to -1 being surrounded by 3 ninjas in one turn. I think this is okay, but I'm not sure.

**Comment by wangx6f** [comment]
1.I will fixed the spy lives problem
2.I think the MAX bullet is 1 so there is no way to have 2 bullet

**Comment by wangx6f** [comment]
I will also fix the lost more than 1 lives in a turn also.
