### ISSUE TITLE
Ninja's movement 

### ISSUE THREAD

**Issue by eyMiko** [Donhavich/CS-project#11]
I'm not sure if this is an issue, but I've noticed that after I use a turn to kill a ninja, the other ninjas don't move afterwards, until I make a movement. In other words, choosing the option to shoot is supposed to count as a turn, thus the ninjas are supposed to move, but they are all still frozen until I move the character. Also, in the beginning of the game, the ninja overlapped the spy by spawning on top of him. And immediately after, when I move away from the ninja, one of the ninjas right next to me disappears. I think it might be the ninja is overlapping with another ninja.

**Comment by wangx6f** [comment]
For the first issue, I think shooting is not supposed to count as a turn, so after shoot the ninjas won't move. For the second issue, I am not sure how it happens cause in my run,it didn't act like that.

**Comment by eyMiko** [comment]
The second issue rarely occurs, because it only happened twice for me.
