### ISSUE TITLE
Problems so far. 

### ISSUE THREAD

**Issue by eyMiko** [Donhavich/CS-project#9]
When I first started the game, the ninja spawned on top of me and killed me right when I moved one space. I think the spy is suppose to have like a 3x3 safezone. And in one instance of the game, a ninja disappeared from the screen and reappeared right next to me. Whenever I die, the count of my bullets are reset to 1. I know that the game is supposed to remain the exact same after the spy dies, with the same position, but is the amount of bullets suppose to be reset to 1? When I input something invalid, the system catches it. But if I do it two times in a row, it gives me an error. That's all I found so far, but I'll test more cases out. And just a suggestion, but maybe the player should have an option of making a new game if they can't load the game?

**Comment by wangx6f** [comment]
1.I am not sure how the ninja appears in the savezone at the beginning of the game, and I do have some code to control it not to be in those spots.
2.I didn't see the bullet reset problem in my running
3.I already solved the invalid input problem and updated the code
4.I will add a new game option when there is not game to load later on
